version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\ssr
init:
- cmd: >-
    echo %APPVEYOR_BUILD_WORKER_IMAGE%

    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017 Win64" )

    echo %generator%
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake .. -G %generator%
build:
  project: c:\ssr\build\Screen Space Reflection.sln
  verbosity: minimal