// Rayleigh
#ifdef __cplusplus
#pragma once
#define CONSTANT constexpr
#else
#define CONSTANT static const
#endif

CONSTANT int TRANSMITTANCE_W = 256;
CONSTANT int TRANSMITTANCE_H = 64;

CONSTANT int TRANSMITTANCE_GROUP_X = 8;
CONSTANT int TRANSMITTANCE_GROUP_Y = 4;

CONSTANT int IRRADIANCE_W = 64;
CONSTANT int IRRADIANCE_H = 16;

CONSTANT int IRRADIANCE_GROUP_X = 1; 
CONSTANT int IRRADIANCE_GROUP_Y = 1;

CONSTANT int RES_R = 32;
CONSTANT int RES_MU = 128;
CONSTANT int RES_MU_S = 32;
CONSTANT int RES_NU = 8;

CONSTANT int INSCATTER1_GROUP_X = RES_NU;
CONSTANT int INSCATTER1_GROUP_Y = 4;
CONSTANT int INSCATTER1_GROUP_Z = RES_R;

CONSTANT int INSCATTERS_GROUP_X = RES_NU * 4;
CONSTANT int INSCATTERS_GROUP_Y = 4;
CONSTANT int INSCATTERS_GROUP_Z = RES_R;

CONSTANT int INSCATTERN_GROUP_X = RES_NU;
CONSTANT int INSCATTERN_GROUP_Y = 4;
CONSTANT int INSCATTERN_GROUP_Z = RES_R;
